<?php
/**
 * @file
 * Slack integration module.
 */

module_load_include('inc', 'drupal_slack', 'includes/ds_functions');

/*=================================
              HOOKS
 ================================*/

/**
 * Implements hook_menu().
 * @return array
 */
function drupal_slack_menu() {
  $items = array();

  $items['admin/config/user-interface/drupal_slack'] = array(
    'title' => 'Drupal Slack settings',
    'description' => 'Description of your On this date settings page',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('drupal_slack_admin'),
    'access arguments' => array('administer drupal_slack settings'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_admin().
 * @return mixed
 */
function drupal_slack_admin() {
  $form = array();

  $form['ds_domain'] = array(
    '#type' => 'textfield',
    '#title' => t('Domain'),
    '#default_value' => variable_get('ds_domain'),
    '#size' => 60,
    '#maxlength' => 128,
    '#description' => t("Slack domain, for example 'https://api.slack.com'."),
    '#required' => TRUE,
  );

  $form['ds_channel'] = array(
    '#type' => 'textfield',
    '#title' => t('Channel ID'),
    '#default_value' => variable_get('ds_channel'),
    '#size' => 60,
    '#maxlength' => 128,
    '#required' => TRUE,
  );

  $form['ds_token'] = array(
    '#type' => 'textfield',
    '#title' => t('Channel Token'),
    '#default_value' => variable_get('ds_token'),
    '#size' => 60,
    '#maxlength' => 128,
    '#required' => TRUE,
  );

  $form['ds_msg_number'] = array(
    '#type' => 'textfield',
    '#title' => t('Number of displayed messages'),
    '#default_value' => variable_get('ds_msg_number'),
    '#size' => 2,
    '#maxlength' => 2,
  );

  return system_settings_form($form);
}

/**
 * Implements hook_block_info().
 * @return array
 */
function drupal_slack_block_info() {
  $number = variable_get('ds_msg_number', '');

  $blocks = array();
  $blocks['drupal_slack_messages'] = array(
    'info' => t("Slack messages"),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 * @param string $delta
 * @return array
 */
function drupal_slack_block_view($delta = '') {
  $blocks = array();

  switch($delta) {
    case 'drupal_slack_messages':
      $result = ds_get_messages();

      if (empty($result)) {
        $blocks['content'] = t('No messages.');
      } else {
        $blocks['content'] = $result;
      }
      $blocks['subject'] = t('Slack messages');
      break;
  }

  return $blocks;
}

/**
 * Implements hook_theme().
 * @return array
 */
function drupal_slack_theme() {
  return array(
    'slack_messages' => array(
      'variables' => array(
        'messages' => NULL
      ),
      'template' => 'templates/slack_messages',
    ),
  );
}
